- project:
    merge-mode: squash-merge
    default-branch: main
    check:
      jobs:
        - otc-tox-linters
        - zuul-config-build-image-f37
        - zuul-config-build-image-f38
        - zuul-config-build-image-f39
    gate:
      jobs:
        - otc-tox-linters
        - zuul-config-build-image-f37
        - zuul-config-build-image-f38
        - zuul-config-build-image-f39
    post:
      jobs:
        - zuul-config-upload-image-f37
        - zuul-config-upload-image-f38
        - zuul-config-upload-image-f39
