- project:
    merge-mode: squash-merge
    check:
      jobs:
        - zuul-config-build-image-f34
    gate:
      jobs:
        - zuul-config-build-image-f34
    post:
      jobs:
        - zuul-config-upload-image-f34

